# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: x
# disqus-ID: x
# utterances-repo: x

menu:
- {name: '',    file: ''}
- {name: 'Retrieval', file: 'retrieval.html'}
# - {name: 'Clustering', file: 'clustering.html'}
- {name: 'Classification', file: 'classification.html'}
# - {name: 'Seq2seq', file: 'seq2seq.html'}
# - {name: 'Object detection', file: 'objdet.html'}
# - {name: 'GNN and RL', file: 'gnn.html'}
# - {name: 'Datasets', file: 'datasets.html'}
# - {name: 'Knowledge Base', url: 'https://dell-research-harvard.github.io/blog.html'}

# - {name: 'Team',     file: 'team.html'}

social:

publication: 
    types:
      - 'Publications'
      - 'Working Papers'
    topics:
      - {name: 'All',            id: 'all',  description: ''}
      - {name: 'Publications',  id: 'pub',   description: ''}
      - {name: 'Working Papers',            id: 'wp',  description: ''}
      - {name: 'Other',          id: 'misc', description: ''}
    default_img: "/assets/publications/placeholder.png"
    tag_list: 
      - {name: "paper",  icon: "far fa-file-pdf"}
      - {name: "website",icon: "fas fa-globe-americas"}
      - {name: "arxiv",  icon: "ai ai-arxiv"}  
      - {name: "poster", icon: "far fa-file-image"}
      - {name: "video",  icon: "fab fa-youtube"}

people:
  roles: 
    - {name: 'predocs', template: "team/full-card.html"}
  tags: 
    - {name: "email",  icon: "fas fa-paper-plane"}
    - {name: "website",  icon: "fas fa-globe-americas"}
    - {name: "google_scholar",  icon: "ai ai-google-scholar-square"}

    
resources:
  categories:
    - {name: 'software', color: 'is-primary'}
  tags: 
    - {name: "paper",  icon: "far fa-file-pdf"}
    - {name: "website",icon: "fas fa-globe-americas"}
    - {name: "github", icon: "fab fa-github"}  

posts:
  video: 
    url: 
    title:  